///////////////////////////////////////////////////////////
//  Attack.cs
//  Implementation of the Class Mage
//  Generated by Enterprise Architect
//  Created on:      16-Oct-2017 9:31:30 AM
//  Original author: tbaird
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Mage : PlayerCharacter {

	public Mage(){

	}

	~Mage(){

	}

	/// <summary>
	/// Calls base Constructor and passes parameters through
	/// 
	/// ***
	/// 
	/// Assigned a New FIREBALL to the SpecialAttack attribute
	/// </summary>
	/// <param name="BaseDam"></param>
	/// <param name="MaxHealth"></param>
	/// <param name="CharName"></param>
	public Mage(int BaseDam, int MaxHealth, string CharName){

	}

}//end Mage