///////////////////////////////////////////////////////////
//  Berserk.cs
//  Implementation of the Class SpecialAttack
//  Generated by Enterprise Architect
//  Created on:      16-Oct-2017 9:31:31 AM
//  Original author: tbaird
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public abstract class SpecialAttack : Attack {

	public SpecialAttack(){

	}

	~SpecialAttack(){

	}

}//end SpecialAttack