///////////////////////////////////////////////////////////
//  Fireball.cs
//  Implementation of the Class Attack
//  Generated by Enterprise Architect
//  Created on:      16-Oct-2017 9:31:32 AM
//  Original author: tbaird
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public abstract class Attack {

	public Attack(){

	}

	~Attack(){

	}

	public abstract int GetAttackResult();

}//end Attack