///////////////////////////////////////////////////////////
//  GameController.cs
//  Implementation of the Class GameController
//  Generated by Enterprise Architect
//  Created on:      16-Oct-2017 9:31:32 AM
//  Original author: tbaird
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class GameController {

	private NonPlayerCharacter enemy;
	private PlayerCharacter player;
	public PlayerCharacter m_PlayerCharacter;
	public NonPlayerCharacter m_NonPlayerCharacter;

	public GameController(){

	}

	~GameController(){

	}

	/// <summary>
	/// this will take one of :
	/// 
	/// mage, thief or warrior as a parameter and create an instance of that class,
	/// assigning the result to the player character variable in the game controller.
	/// </summary>
	/// <param name="class"></param>
	public void ChooseClass(string Class)
    {

	}

	public void normalAttack(){

	}

	public void specialAttack(){

	}

	public void startBattle(){

	}

}//end GameController