///////////////////////////////////////////////////////////
//  NonPlayerCharacter.cs
//  Implementation of the Class Berserk
//  Generated by Enterprise Architect
//  Created on:      16-Oct-2017 9:31:32 AM
//  Original author: tbaird
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Berserk : SpecialAttack {

	public Berserk(){

	}

	~Berserk(){

	}

	/// <summary>
	/// This is an override of the Attack:GetAttackResult()
	/// 
	/// +ve return is damage applied to NPC
	/// -ve return is damage applied to PC
	/// 0 return is no damage done.
	/// </summary>
	public int GetAttackResult(){

		return 0;
	}

}//end Berserk