///////////////////////////////////////////////////////////
//  NormalAttack.cs
//  Implementation of the Class PlayerCharacter
//  Generated by Enterprise Architect
//  Created on:      16-Oct-2017 9:31:30 AM
//  Original author: tbaird
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public abstract class PlayerCharacter : Character {

	private char characterName;
	private NormalAttack normalAttack;
	private SpecialAttack specialAttack;
	public NormalAttack m_NormalAttack;
	public SpecialAttack m_SpecialAttack;

	public PlayerCharacter(){

	}

	~PlayerCharacter(){

	}

	public int GetNormalAttackResult(){

		return 0;
	}

	/// <summary>
	/// This returns an int which represents the damage done by the special attack
	/// 
	/// +ve int means damage done to NPC
	/// -ve int means damage done to player
	/// 0 mean no damage done
	/// </summary>
	public abstract int GetSpecialAttackResult();

}//end PlayerCharacter