///////////////////////////////////////////////////////////
//  SpecialAttack.cs
//  Implementation of the Class NonPlayerCharacter
//  Generated by Enterprise Architect
//  Created on:      16-Oct-2017 9:31:30 AM
//  Original author: tbaird
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class NonPlayerCharacter : Character {

	private NormalAttack attack;
	/// <summary>
	/// e.g. goblin, giant etc
	/// </summary>
	private char enemyType;
	public NormalAttack m_NormalAttack;

	public NonPlayerCharacter(){

	}

	~NonPlayerCharacter(){

	}

	public int GetNomalAttackResult(){

		return 0;
	}

}//end NonPlayerCharacter