///////////////////////////////////////////////////////////
//  Thief.cs
//  Implementation of the Class Character
//  Generated by Enterprise Architect
//  Created on:      16-Oct-2017 9:31:29 AM
//  Original author: tbaird
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public abstract class Character {

	private int baseDamage;
	private int currentHealthPoints;
	private int maxHealthPoints;

	public Character(){

	}

	~Character(){

	}

	/// <summary>
	/// returns character health after damage applied
	/// </summary>
	/// <param name="pAmount"></param>
	public int TakeDamage(int pAmount){

		return 0;
	}

}//end Character