///////////////////////////////////////////////////////////
//  Warrior.cs
//  Implementation of the Class Warrior
//  Generated by Enterprise Architect
//  Created on:      16-Oct-2017 9:31:31 AM
//  Original author: tbaird
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Warrior : PlayerCharacter {

	public Warrior(){

	}

	~Warrior(){

	}

	/// <summary>
	/// Calls base Constructor and passes parameters through
	/// 
	/// ***
	/// 
	/// Assigned a New FIREBALL to the SpecialAttack attribute
	/// </summary>
	/// <param name="BaseDam"></param>
	/// <param name="MaxHealth"></param>
	/// <param name="CharName"></param>
	public Warrior(int BaseDam, int MaxHealth, string CharName){

	}

}//end Warrior